# Generated by Django 5.2.7 on 2025-10-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
